/*
 */

#include "nsISupports.idl"

/*
 *
 */
[scriptable, uuid(32067828-1dd2-11b2-8c5b-ec25e8be3bc2)]
interface sbISoundCloudService : nsISupports 
{	

  attribute AString nowplaying_url;
  //attribute boolean autoLogin;
  //attribute boolean loggedIn;

};
